<?xml version="1.0" encoding="UTF-8"?>

<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	name="CarReservationWrapper"
	targetNamespace="http://ws.car.soa.jael.lsd.ic.unicamp.br/"
	xmlns:tns="http://ws.car.soa.jael.lsd.ic.unicamp.br/"
	xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
	xmlns:ns="http://ws.car.soa.jael.lsd.ic.unicamp.br/">
	
	<import location="CarReservation.wsdl" namespace="http://ws.car.soa.jael.lsd.ic.unicamp.br/" />
	
	<plnk:partnerLinkType name="CarReservationLinkType">
		<plnk:role name="CarReservationRole" portType="ns:CarReservation" />
	</plnk:partnerLinkType>
</definitions>
